name: build-doc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install mdbook
      run: cargo install mdbook --version 0.4.15
    - name: Build docs
      run: mdbook build
    - name: Add & Commit
      uses: EndBug/add-and-commit@v8.0.0
      with:
          add: 'docs --force'
          message: 'rebuild docs'
 
